/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package QuanLySanPham;

import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author h
 */
public class DsSanPham extends javax.swing.JPanel {

    /** Creates new form DsDiaPhim */
    public DsSanPham() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDanhSachCacSanPham = new javax.swing.JLabel();
        ScrPaneTable = new javax.swing.JScrollPane();
        tableDsSanPham = new javax.swing.JTable();
        btSuaDsCacSp = new javax.swing.JButton();
        btXoaDsCacSp = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));

        lbDanhSachCacSanPham.setText("Danh Sách Các Sản Phẩm");

        tableDsSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã MH", "Tên MH", "Loại MH", "Thể Loại", "Số lượng", "Giá mua", "Giá bán"
            }
        ));
        ScrPaneTable.setViewportView(tableDsSanPham);

        btSuaDsCacSp.setText("Sửa");
        btSuaDsCacSp.setPreferredSize(new java.awt.Dimension(85, 23));

        btXoaDsCacSp.setText("Xóa");
        btXoaDsCacSp.setPreferredSize(new java.awt.Dimension(85, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDanhSachCacSanPham)
                .addGap(363, 363, 363))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrPaneTable)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(btSuaDsCacSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btXoaDsCacSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDanhSachCacSanPham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(ScrPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSuaDsCacSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoaDsCacSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getScrPaneTable() {
        return ScrPaneTable;
    }

    public JTable getTableDsSanPham() {
        return tableDsSanPham;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrPaneTable;
    private javax.swing.JButton btSuaDsCacSp;
    private javax.swing.JButton btXoaDsCacSp;
    private javax.swing.JLabel lbDanhSachCacSanPham;
    private javax.swing.JTable tableDsSanPham;
    // End of variables declaration//GEN-END:variables

}
