/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLySanPham;

/**
 *
 * @author h
 */
public class NhapHang extends javax.swing.JPanel {

    /**
     * Creates new form NhapHang
     */
    public NhapHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNhapHang = new javax.swing.JLabel();
        PanelInfoNhapHang = new javax.swing.JPanel();
        lbMaMh = new javax.swing.JLabel();
        lbTenMatHangNhapHang = new javax.swing.JLabel();
        lbLoaiMatHangNhapHang = new javax.swing.JLabel();
        lbSoLuongNhapHang = new javax.swing.JLabel();
        lbGiaMuaNhapHang = new javax.swing.JLabel();
        lbGiaBanNhapHang = new javax.swing.JLabel();
        txtfMatHangNhapHang = new javax.swing.JTextField();
        txtfTenMatHangNhapHang = new javax.swing.JTextField();
        txtfSoLuongNhapHang = new javax.swing.JTextField();
        txtfGiaMuaNhapHang = new javax.swing.JTextField();
        txtfGiaBanNhapHang = new javax.swing.JTextField();
        comBLoaiMHNhapHang = new javax.swing.JComboBox<>();
        PanelReferenceNhapHang = new javax.swing.JPanel();
        lbRef1NhapHang = new javax.swing.JLabel();
        lbRef2NhapHang = new javax.swing.JLabel();
        lbRef3NhapHang = new javax.swing.JLabel();
        txtfRef1NhapHang = new javax.swing.JTextField();
        txtfRef2NhapHang = new javax.swing.JTextField();
        txtfRef3NhapHang = new javax.swing.JTextField();
        lbTheLoaiNhapHang = new javax.swing.JLabel();
        txtfTheLoaiNhapHang = new javax.swing.JTextField();
        btXoaNhapHang = new javax.swing.JButton();
        btLuuNhapHang = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));

        lbNhapHang.setText("Nhập hàng");

        lbMaMh.setText("Mã Mặt Hàng");

        lbTenMatHangNhapHang.setText("Tên Mặt Hàng");

        lbLoaiMatHangNhapHang.setText("Loại Mặt Hàng");

        lbSoLuongNhapHang.setText("Số Lượng");

        lbGiaMuaNhapHang.setText("Giá Mua");

        lbGiaBanNhapHang.setText("Giá Bán");

        comBLoaiMHNhapHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đĩa Nhạc", "Đĩa Phim", "Các Loại Sách" }));
        comBLoaiMHNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBLoaiMHNhapHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInfoNhapHangLayout = new javax.swing.GroupLayout(PanelInfoNhapHang);
        PanelInfoNhapHang.setLayout(PanelInfoNhapHangLayout);
        PanelInfoNhapHangLayout.setHorizontalGroup(
            PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaMh)
                    .addComponent(lbTenMatHangNhapHang)
                    .addComponent(lbLoaiMatHangNhapHang)
                    .addComponent(lbSoLuongNhapHang)
                    .addComponent(lbGiaMuaNhapHang)
                    .addComponent(lbGiaBanNhapHang))
                .addGap(120, 120, 120)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtfMatHangNhapHang)
                        .addComponent(txtfTenMatHangNhapHang)
                        .addComponent(txtfSoLuongNhapHang)
                        .addComponent(txtfGiaMuaNhapHang)
                        .addComponent(txtfGiaBanNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                    .addComponent(comBLoaiMHNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        PanelInfoNhapHangLayout.setVerticalGroup(
            PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoNhapHangLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaMh)
                    .addComponent(txtfMatHangNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenMatHangNhapHang)
                    .addComponent(txtfTenMatHangNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoaiMatHangNhapHang)
                    .addComponent(comBLoaiMHNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoLuongNhapHang)
                    .addComponent(txtfSoLuongNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGiaMuaNhapHang)
                    .addComponent(txtfGiaMuaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGiaBanNhapHang)
                    .addComponent(txtfGiaBanNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbRef1NhapHang.setText("Nhạc sĩ");

        lbRef2NhapHang.setText("Ca sĩ");

        lbRef3NhapHang.setText("Albumn");

        lbTheLoaiNhapHang.setText("Thể Loại");

        javax.swing.GroupLayout PanelReferenceNhapHangLayout = new javax.swing.GroupLayout(PanelReferenceNhapHang);
        PanelReferenceNhapHang.setLayout(PanelReferenceNhapHangLayout);
        PanelReferenceNhapHangLayout.setHorizontalGroup(
            PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReferenceNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRef1NhapHang)
                    .addComponent(lbRef2NhapHang)
                    .addComponent(lbRef3NhapHang)
                    .addComponent(lbTheLoaiNhapHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfRef1NhapHang)
                    .addComponent(txtfRef2NhapHang)
                    .addComponent(txtfRef3NhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(txtfTheLoaiNhapHang))
                .addContainerGap())
        );
        PanelReferenceNhapHangLayout.setVerticalGroup(
            PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReferenceNhapHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRef1NhapHang)
                    .addComponent(txtfRef1NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRef2NhapHang)
                    .addComponent(txtfRef2NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRef3NhapHang)
                    .addComponent(txtfRef3NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTheLoaiNhapHang)
                    .addComponent(txtfTheLoaiNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        btXoaNhapHang.setText("Xóa");
        btXoaNhapHang.setPreferredSize(new java.awt.Dimension(85, 23));

        btLuuNhapHang.setText("Lưu");
        btLuuNhapHang.setPreferredSize(new java.awt.Dimension(85, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNhapHang)
                .addGap(357, 357, 357))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelInfoNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelReferenceNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(btXoaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btLuuNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNhapHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelReferenceNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelInfoNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btXoaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLuuNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comBLoaiMHNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBLoaiMHNhapHangActionPerformed
        // TODO add your handling code here:
        String mes = (String) comBLoaiMHNhapHang.getSelectedItem();
        switch(mes){
            case "Đĩa Nhạc":
                lbRef1NhapHang.setText("Nhạc sĩ");
                lbRef2NhapHang.setText("Ca sĩ");
                lbRef3NhapHang.setText("Albumn");
                break;
            case "Đĩa Phim":
                lbRef1NhapHang.setText("Đạo diễn");
                lbRef2NhapHang.setText("Diễn viên");
                lbRef3NhapHang.setText("Chất lượng");
                break;
            default:
                lbRef1NhapHang.setText("Tác giả");
                lbRef2NhapHang.setText("NXB");
                lbRef3NhapHang.setText("Ngôn ngữ");
                break;
        }
    }//GEN-LAST:event_comBLoaiMHNhapHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfoNhapHang;
    private javax.swing.JPanel PanelReferenceNhapHang;
    private javax.swing.JButton btLuuNhapHang;
    private javax.swing.JButton btXoaNhapHang;
    private javax.swing.JComboBox<String> comBLoaiMHNhapHang;
    private javax.swing.JLabel lbGiaBanNhapHang;
    private javax.swing.JLabel lbGiaMuaNhapHang;
    private javax.swing.JLabel lbLoaiMatHangNhapHang;
    private javax.swing.JLabel lbMaMh;
    private javax.swing.JLabel lbNhapHang;
    private javax.swing.JLabel lbRef1NhapHang;
    private javax.swing.JLabel lbRef2NhapHang;
    private javax.swing.JLabel lbRef3NhapHang;
    private javax.swing.JLabel lbSoLuongNhapHang;
    private javax.swing.JLabel lbTenMatHangNhapHang;
    private javax.swing.JLabel lbTheLoaiNhapHang;
    private javax.swing.JTextField txtfGiaBanNhapHang;
    private javax.swing.JTextField txtfGiaMuaNhapHang;
    private javax.swing.JTextField txtfMatHangNhapHang;
    private javax.swing.JTextField txtfRef1NhapHang;
    private javax.swing.JTextField txtfRef2NhapHang;
    private javax.swing.JTextField txtfRef3NhapHang;
    private javax.swing.JTextField txtfSoLuongNhapHang;
    private javax.swing.JTextField txtfTenMatHangNhapHang;
    private javax.swing.JTextField txtfTheLoaiNhapHang;
    // End of variables declaration//GEN-END:variables
}
